apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    app: nginx
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
      - containerPort: 80
        name: http
    volumeMounts:
      - name: nginx-config
        mountPath: /etc/nginx/default.conf
        subPath: nginx.conf
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
  - name: nginx-exporter
    image: 'nginx/nginx-prometheus-exporter:latest'
    args:
      - '-nginx.scrape-uri=http://localhost/metrics'
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 9113
        name: metrics
  volumes:  
    - name: nginx-config
      configMap:
        name: nginx-config
        defaultMode: 420
