apiVersion: v1
kind: Pod
metadata:
  name: pod
  labels:
    app: nginx-deployment
spec:
  containers:
  - name: nginx-deployment
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
