apiVersion: v1
data:
  nginx.conf: |-
    http {
        server {
            listen 80;
            listen 443 ssl;
            ssl_certificate /etc/nginx/tls/certificado.certificado;
            ssl_certificate /etc/nginx/tls/chave-privada.key;

            location /
              return 200 'Olá terraqueos!\n';
              add_header Content-Type text/plain;
        }
    }
kind: ConfigMap
metadata:
  creationTimestamp: "2025-02-20T21:46:49Z"
  name: nginx-config
