apiVersion: v1
kind: Pod
metadata:
  name: meu-pod
  labels:
    name: meu-pod
spec:
  containers:
  - name: meu-container
    image: linuxtips/opa
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
  imagePullSecrets:
  - name: dockerhub-test
